
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm


# Requests for API endpoints of the sample project:

### Hello world endpoint: get response "Hello, Stranger!"
GET http://localhost:8080/hello-world


### Hello world with a request param passed.
# When sending the request it will ask you for the name
# hitting enter will avoid passing the param, and do the default behaviour above
# @prompt name The name to display in response
GET http://localhost:8080/hello-world
    ?name={{name}}

### Save a greeting to database
@postGreetingId = 1001
@postGreetingContent = Hello!
POST http://localhost:8080/greetings
Content-Type: application/json

{
    "id": "{{postGreetingId}}",
    "content": "{{postGreetingContent}}"
}

### Get all greetings
GET http://localhost:8080/greetings

### Get info for greeting with given content
# @prompt content Greeting content to look for, defaults to "Overview"
GET http://localhost:8080/info
    ?title={{content}}

### Update an existing greeting
@putGreetingId = 1001
@putGreetingContent = Hello again!
PUT http://localhost:8080/greetings/{{putGreetingId}}
Content-Type: application/json

{
    "content": "{{putGreetingContent}}"
}

### Delete greeting
@deleteGreetingId = 1001
DELETE http://localhost:8080/greetings/{{deleteGreetingId}}


# TODO add requests for your own endpoints!

//register readers

POST http://localhost:8080/auth/register/reader
Content-Type: application/json

{
  "name": "nume2",
  "password": "parola_utilizator2",
  "email": "email2@exemplu.com"
}

//register librarians

POST http://localhost:8080/auth/register/librarian
Content-Type: application/json

{
  "name": "nume",
  "password": "parola",
  "email": "emaillib@exemplu.com"
}

//login reader

POST http://localhost:8080/auth/login?email=email2@exemplu.com&password=parola_utilizator2

//login librarian

POST http://localhost:8080/auth/login?email=emaillib@exemplu.com&password=parola

//add book by librarian

POST http://localhost:8080/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWxsaWJAZXhlbXBsdS5jb20iLCJpYXQiOjE3NDIzMDM1NjksImV4cCI6MTc0MjMzOTU2OX0.1DA_o0OReGAqcwyh5mxCbtErVy5V_5-lqkfMs6M0hDI
Content-Type: application/json

{
  "title": "A Game of Thrones",
  "author": "George R.R. Martin",
  "genre": "Fiction",
  "copies": 1
}

//rent book by book id

POST http://localhost:8080/rent?bookId=67d97187ae0eb30eac9de288
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbDJAZXhlbXBsdS5jb20iLCJpYXQiOjE3NDIzMDM3NDgsImV4cCI6MTc0MjMzOTc0OH0.ablYPxZrgJg5JvLiSzoK7aa1JsOsIEa9XkG5wIn51lU

//rent book by title
//not working

POST http://localhost:8080/rentbytitle
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbEBleGVtcGx1LmNvbSIsImlhdCI6MTc0MjA2NDk1OSwiZXhwIjoxNzQyMTAwOTU5fQ.Ow9Q6ZhZnWNEROk3QZGQCUc0lvlq4E6N8J1t1cPDHIM
Content-Type: application/json

{
  "title": "Hunger Games"
}

// return book

POST http://localhost:8080/return?bookId=67d7ed255b85841f81f32548
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbDNAZXhlbXBsdS5jb20iLCJpYXQiOjE3NDIyMDYwNzYsImV4cCI6MTc0MjI0MjA3Nn0.yWUzSvGrvO2c78ZmDINL6UUjzddXXwuglEQwRhMo1Cs

//get all books
GET http://localhost:8080/books/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//update book by id
PUT http://localhost:8080/books/update/67d7dc2def41f60d84d7b30d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8
Content-Type: application/json

{
  "title": "Game of Thrones",
  "author": "George R.R. Martin",
  "genre": "Fiction",
  "availability": "AVAILABLE"
}

//delete book by id
DELETE http://localhost:8080/books/delete/67d7dc2def41f60d84d7b30d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8


//get all readers
GET http://localhost:8080/readers/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//get all readers with books rented
GET http://localhost:8080/readers/borrowers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//get all reader with late books
GET http://localhost:8080/readers/late
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//ban all readers with late books
POST http://localhost:8080/readers/banlate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//get all banned readers
GET http://localhost:8080/readers/banned
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

//unban reader
POST http://localhost:8080/readers/unban/67d7dba4ef41f60d84d7b30b
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

// reserve book (you see the number you are at the que) (reader)
POST http://localhost:8080/reserve/book?bookId=67d7ed255b85841f81f32548
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbDRAZXhlbXBsdS5jb20iLCJpYXQiOjE3NDIyMDYwMTEsImV4cCI6MTc0MjI0MjAxMX0.smyhN3Jy5_OUbCus0lUqlonBTwgbtBnJSLqOPu20wT8

// unreserve book (reader)
POST http://localhost:8080/reserve/unreserve?bookId=67d69d9e900fd079c81232d3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbDIyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMTMzNzMxLCJleHAiOjE3NDIxNjk3MzF9.iS7eTXbvjlZgA6mragmKCwjd-MPr0NNbHENb24eSmcU

// see reserve list with bookid (admin)
GET http://localhost:8080/reserve/list/67d7dd98ef41f60d84d7b30e
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMjAwMDMyLCJleHAiOjE3NDIyMzYwMzJ9.D_mmNDvZXf8M5zjnRynZptjACvhoGtfkMxdurcA2Qc8

// see your reservations (reader)
GET http://localhost:8080/reserve/my-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbDRAZXhlbXBsdS5jb20iLCJpYXQiOjE3NDIyMDg3MDEsImV4cCI6MTc0MjI0NDcwMX0.RWEtsAD35BCijwiNr52F4Pv4BZwK-voCbRsGexyc90o