
# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial?srsltid=AfmBOoppDqtkhRxj5BLZONRZFzRDmh6eP-xyTo6H4OuEHYuVbrg1d4Dm


# Requests for API endpoints of the sample project:

### Hello world endpoint: get response "Hello, Stranger!"
GET http://localhost:8080/hello-world


### Hello world with a request param passed.
# When sending the request it will ask you for the name
# hitting enter will avoid passing the param, and do the default behaviour above
# @prompt name The name to display in response
GET http://localhost:8080/hello-world
    ?name={{name}}

### Save a greeting to database
@postGreetingId = 1001
@postGreetingContent = Hello!
POST http://localhost:8080/greetings
Content-Type: application/json

{
    "id": "{{postGreetingId}}",
    "content": "{{postGreetingContent}}"
}

### Get all greetings
GET http://localhost:8080/greetings

### Get info for greeting with given content
# @prompt content Greeting content to look for, defaults to "Overview"
GET http://localhost:8080/info
    ?title={{content}}

### Update an existing greeting
@putGreetingId = 1001
@putGreetingContent = Hello again!
PUT http://localhost:8080/greetings/{{putGreetingId}}
Content-Type: application/json

{
    "content": "{{putGreetingContent}}"
}

### Delete greeting
@deleteGreetingId = 1001
DELETE http://localhost:8080/greetings/{{deleteGreetingId}}


# TODO add requests for your own endpoints!

//register readers

POST http://localhost:8080/auth/register/reader
Content-Type: application/json

{
  "name": "nume_utilizator",
  "password": "parola_utilizator",
  "email": "email1@exemplu.com"
}

//register librarians

POST http://localhost:8080/auth/register/librarian
Content-Type: application/json

{
  "name": "nume",
  "password": "parola",
  "email": "email2@exemplu.com"
}

//login reader

POST http://localhost:8080/auth/login?email=email@exemplu.com&password=parola_utilizator

//login librarian

POST http://localhost:8080/auth/login?email=email2@exemplu.com&password=parola

//add book by librarian

POST http://localhost:8080/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOIiwic3ViIjoiZW1haWwyQGV4ZW1wbHUuY29tIiwiaWF0IjoxNzQyMDU4MDk4LCJleHAiOjE3NDIwOTQwOTh9.F_ictLyD4ovO8sFvIZPy4vgIM9uMUoFF_ZfCqb51ka4
Content-Type: application/json

{
  "title": "Hunger Games",
  "author": "Suzanne Collins",
  "genre": "Fiction",
  "availability": "AVAILABLE"
}

//rent book by book id

POST http://localhost:8080/rent?bookId=67d5b2c57fcdff5948f08903
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbEBleGVtcGx1LmNvbSIsImlhdCI6MTc0MjA2NDk1OSwiZXhwIjoxNzQyMTAwOTU5fQ.Ow9Q6ZhZnWNEROk3QZGQCUc0lvlq4E6N8J1t1cPDHIM

//rent book by title
//not working

POST http://localhost:8080/rentbytitle
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbEBleGVtcGx1LmNvbSIsImlhdCI6MTc0MjA2NDk1OSwiZXhwIjoxNzQyMTAwOTU5fQ.Ow9Q6ZhZnWNEROk3QZGQCUc0lvlq4E6N8J1t1cPDHIM
Content-Type: application/json

{
  "title": "Hunger Games"
}

// return book

POST http://localhost:8080/return?bookId=67d5b2c57fcdff5948f08903
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IlVTRVIiLCJzdWIiOiJlbWFpbEBleGVtcGx1LmNvbSIsImlhdCI6MTc0MjA2NDk1OSwiZXhwIjoxNzQyMTAwOTU5fQ.Ow9Q6ZhZnWNEROk3QZGQCUc0lvlq4E6N8J1t1cPDHIM
